# Generated by Django 4.1.1 on 2022-10-27 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'two_wheeler'), ('three_wheeler', 'three_wheeler'), ('four_wheeler', 'four_wheeler')], max_length=14)),
                ('vehicle_model', models.CharField(max_length=25)),
                ('vehicle_description', models.CharField(max_length=200)),
            ],
        ),
    ]
